target-version = "py311"
line-length = 100
src = ["app", "tests", "scripts"]

[lint]
select = ["E", "F", "W", "I", "UP", "B"]
ignore = ["E501", "B008"]
fixable = ["ALL"]

[lint.per-file-ignores]
"scripts/**/*.py" = ["E402"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
